import { Item } from "./model";

export const sampleNames = [
  "Aaden",
  "Aarav",
  "Aaron",
  "Abdiel",
  "Abdullah",
  "Abel",
  "Abraham",
  "Abram",
  "Ace",
  "Adam",
  "Adan",
  "Aden",
  "Adrian",
  "Adriel",
  "Aidan",
  "Aiden",
  "Alan",
  "Albert",
  "Alberto",
  "Alec",
  "Alejandro",
  "Alex",
  "Alexander",
  "Alexis",
  "Alfonso",
  "Alfred",
  "Alfredo",
  "Ali",
  "Allan",
  "Allen",
  "Alonso",
  "Alonzo",
  "Alvaro",
  "Alvin",
  "Amari",
  "Ameer",
  "Amir",
  "Amos",
  "Andre",
  "Andres",
  "Andrew",
  "Andy",
  "Angel",
  "Angelo",
  "Anthony",
  "Antonio",
  "Archer",
  "Ari",
  "Ariel",
  "Armando",
  "Armani",
  "Arnold",
  "Arthur",
  "Arturo",
  "Ashton",
  "Atlas",
  "Atticus",
  "August",
  "Augustine",
  "Augustus",
  "Austin",
  "Avery",
  "Axel",
  "Ayden",
  "Beau",
  "Beckham",
  "Ben",
  "Benjamin",
  "Bennett",
  "Bentley",
  "Blake",
  "Bobby",
  "Boden",
  "Braden",
  "Bradley",
  "Brady",
  "Brandon",
  "Braxton",
  "Brayden",
  "Brendan",
  "Brian",
  "Brody",
  "Brooks",
  "Bruce",
  "Bruno",
  "Bryan",
  "Bryce",
  "Bryson",
  "Caden",
  "Caleb",
  "Calvin",
  "Camden",
  "Cameron",
  "Carlos",
  "Carson",
  "Carter",
  "Case",
  "Casey",
  "Cash",
  "Cayden",
  "Cesar",
  "Chad",
  "Chance",
  "Charles",
  "Charlie",
  "Chase",
  "Christian",
  "Christopher",
  "Clark",
  "Clayton",
  "Cody",
  "Cole",
  "Colin",
  "Colton",
  "Connor",
  "Cooper",
  "Corbin",
  "Corey",
  "Cory",
  "Cruz",
  "Curtis",
  "Cyrus",
  "Dakota",
  "Dallas",
  "Dalton",
  "Damian",
  "Damien",
  "Daniel",
  "Danny",
  "Dante",
  "Darius",
  "David",
  "Davis",
  "Dawson",
  "Dean",
  "Derek",
  "Desmond",
  "Devin",
  "Diego",
  "Dominic",
  "Dominick",
  "Donald",
  "Donovan",
  "Douglas",
  "Drake",
  "Drew",
  "Dylan",
  "Easton",
  "Eddie",
  "Edgar",
  "Edison",
  "Eduardo",
  "Edward",
  "Edwin",
  "Eli",
  "Elias",
  "Elijah",
  "Elliot",
  "Elliott",
  "Ellis",
  "Emerson",
  "Emilio",
  "Emmanuel",
  "Emmett",
  "Enrique",
  "Eric",
  "Erick",
  "Erik",
  "Ernest",
  "Ethan",
  "Eugene",
  "Evan",
  "Everett",
  "Ezekiel",
  "Ezra",
  "Felix",
  "Fernando",
  "Finn",
  "Francis",
  "Francisco",
  "Frank",
  "Franklin",
  "Frederick",
  "Gabriel",
  "Gage",
  "Garrett",
  "Gary",
  "Gavin",
  "George",
  "Gerald",
  "Giovanni",
  "Glenn",
  "Gordon",
  "Graham",
  "Grant",
  "Gray",
  "Grayson",
  "Gregory",
  "Griffin",
  "Gunner",
  "Gustavo",
  "Harold",
  "Harrison",
  "Harry",
  "Harvey",
  "Hayes",
  "Hector",
  "Henry",
  "Hudson",
  "Hugh",
  "Hunter",
  "Ian",
  "Ibrahim",
  "Isaac",
  "Isaiah",
  "Israel",
  "Ivan",
  "Jack",
  "Jackson",
  "Jacob",
  "Jaden",
  "Jake",
  "James",
  "Jameson",
  "Jamie",
  "Jared",
  "Jason",
  "Javier",
  "Jax",
  "Jaxton",
  "Jay",
  "Jayden",
  "Jeffrey",
  "Jeremy",
  "Jerome",
  "Jerry",
  "Jesse",
  "Jesus",
  "Jimmy",
  "Joaquin",
  "Joel",
  "John",
  "Johnny",
  "Jonah",
  "Jonathan",
  "Jordan",
  "Jorge",
  "Jose",
  "Joseph",
  "Joshua",
  "Josiah",
  "Juan",
  "Judah",
  "Jude",
  "Julian",
  "Julio",
  "Julius",
  "Junior",
  "Justin",
  "Kaden",
  "Kai",
  "Kaleb",
  "Kane",
  "Kasen",
  "Kayden",
  "Keith",
  "Kelvin",
  "Kendrick",
  "Kenneth",
  "Kevin",
  "Kian",
  "King",
  "Kingston",
  "Knox",
  "Kobe",
  "Kody",
  "Kolton",
  "Konnor",
  "Kyle",
  "Kyler",
  "Lance",
  "Landon",
  "Larry",
  "Lawrence",
  "Lawson",
  "Layton",
  "Leo",
  "Leon",
  "Leonard",
  "Leonardo",
  "Levi",
  "Lewis",
  "Liam",
  "Lincoln",
  "Logan",
  "Lorenzo",
  "Louis",
  "Luca",
  "Lucas",
  "Luis",
  "Luke",
  "Maddox",
  "Malcolm",
  "Manuel",
  "Marcus",
  "Mario",
  "Mark",
  "Martin",
  "Mason",
  "Mateo",
  "Matthew",
  "Matteo",
  "Max",
  "Maximus",
  "Maxwell",
  "Micah",
  "Michael",
  "Miguel",
  "Miles",
  "Mitchell",
  "Mohamed",
  "Mohammad",
  "Mohammed",
  "Moises",
  "Morgan",
  "Moses",
  "Muhammad",
  "Myles",
  "Nathan",
  "Nathaniel",
  "Nelson",
  "Nicholas",
  "Nicolas",
  "Noah",
  "Nolan",
  "Norman",
  "Oliver",
  "Omar",
  "Orlando",
  "Oscar",
  "Owen",
  "Pablo",
  "Parker",
  "Patrick",
  "Paul",
  "Pedro",
  "Peter",
  "Philip",
  "Phoenix",
  "Pierce",
  "Preston",
  "Prince",
  "Quentin",
  "Quinn",
  "Rafael",
  "Ralph",
  "Ramon",
  "Randy",
  "Raul",
  "Raymond",
  "Reed",
  "Reese",
  "Reid",
  "Remy",
  "Ricardo",
  "Richard",
  "Rick",
  "Riley",
  "River",
  "Robert",
  "Roberto",
  "Robin",
  "Rocco",
  "Rocky",
  "Rodney",
  "Roger",
  "Roman",
  "Ronald",
  "Ronan",
  "Roy",
  "Ruben",
  "Russell",
  "Ryan",
  "Ryder",
  "Salvador",
  "Sam",
  "Samuel",
  "Santiago",
  "Santos",
  "Scott",
  "Sean",
  "Sebastian",
  "Sergio",
  "Seth",
  "Shane",
  "Shawn",
  "Simon",
  "Spencer",
  "Stanley",
  "Stephen",
  "Sterling",
  "Steven",
  "Stone",
  "Sullivan",
  "Tanner",
  "Taylor",
  "Theodore",
  "Thomas",
  "Timothy",
  "Titus",
  "Tobias",
  "Todd",
  "Tom",
  "Tommy",
  "Tony",
  "Travis",
  "Trenton",
  "Trevor",
  "Tristan",
  "Troy",
  "Tucker",
  "Tyler",
  "Tyson",
  "Ulises",
  "Uriel",
  "Valentin",
  "Victor",
  "Vincent",
  "Walter",
  "Warren",
  "Wayne",
  "Wesley",
  "William",
  "Wilson",
  "Wyatt",
  "Xavier",
  "Yahir",
  "Yosef",
  "Zachary",
  "Zander",
  "Zane",
  "Zayden",
  "Zechariah",
  "Zion",
];

export const sampleLocations: Item[] = [
  { type: "state", state: "California" },
  { type: "zip", city: "San Francisco", zip: "94102" },
  { type: "zip", city: "Los Angeles", zip: "90210" },
  { type: "zip", city: "San Diego", zip: "92101" },
  { type: "zip", city: "Sacramento", zip: "95814" },
  { type: "state", state: "New York" },
  { type: "zip", city: "New York City", zip: "10001" },
  { type: "zip", city: "Brooklyn", zip: "11201" },
  { type: "zip", city: "Albany", zip: "12201" },
  { type: "zip", city: "Buffalo", zip: "14201" },
  { type: "state", state: "Texas" },
  { type: "zip", city: "Austin", zip: "73301" },
  { type: "zip", city: "Houston", zip: "77001" },
  { type: "zip", city: "Dallas", zip: "75201" },
  { type: "zip", city: "San Antonio", zip: "78201" },
  { type: "state", state: "Florida" },
  { type: "zip", city: "Miami", zip: "33101" },
  { type: "zip", city: "Orlando", zip: "32801" },
  { type: "zip", city: "Tampa", zip: "33601" },
  { type: "zip", city: "Jacksonville", zip: "32201" },
  { type: "state", state: "Illinois" },
  { type: "zip", city: "Chicago", zip: "60601" },
  { type: "zip", city: "Springfield", zip: "62701" },
  { type: "state", state: "Washington" },
  { type: "zip", city: "Seattle", zip: "98101" },
  { type: "zip", city: "Spokane", zip: "99201" },
  { type: "zip", city: "Tacoma", zip: "98401" },
  { type: "state", state: "Colorado" },
  { type: "zip", city: "Denver", zip: "80201" },
  { type: "zip", city: "Boulder", zip: "80301" },
  { type: "zip", city: "Colorado Springs", zip: "80901" },
  { type: "state", state: "Oregon" },
  { type: "zip", city: "Portland", zip: "97201" },
  { type: "zip", city: "Eugene", zip: "97401" },
  { type: "state", state: "Arizona" },
  { type: "zip", city: "Phoenix", zip: "85001" },
  { type: "zip", city: "Tucson", zip: "85701" },
  { type: "zip", city: "Scottsdale", zip: "85251" },
  { type: "state", state: "Nevada" },
  { type: "zip", city: "Las Vegas", zip: "89101" },
  { type: "zip", city: "Reno", zip: "89501" },
  { type: "state", state: "Georgia" },
  { type: "zip", city: "Atlanta", zip: "30301" },
  { type: "zip", city: "Savannah", zip: "31401" },
  { type: "state", state: "North Carolina" },
  { type: "zip", city: "Charlotte", zip: "28201" },
  { type: "zip", city: "Raleigh", zip: "27601" },
  { type: "zip", city: "Asheville", zip: "28801" },
  { type: "state", state: "Virginia" },
  { type: "zip", city: "Richmond", zip: "23219" },
  { type: "zip", city: "Virginia Beach", zip: "23451" },
  { type: "state", state: "Massachusetts" },
  { type: "zip", city: "Boston", zip: "02101" },
  { type: "zip", city: "Cambridge", zip: "02138" },
  { type: "zip", city: "Worcester", zip: "01601" },
  { type: "state", state: "Pennsylvania" },
  { type: "zip", city: "Philadelphia", zip: "19101" },
  { type: "zip", city: "Pittsburgh", zip: "15201" },
  { type: "state", state: "Ohio" },
  { type: "zip", city: "Columbus", zip: "43201" },
  { type: "zip", city: "Cleveland", zip: "44101" },
  { type: "zip", city: "Cincinnati", zip: "45201" },
  { type: "state", state: "Michigan" },
  { type: "zip", city: "Detroit", zip: "48201" },
  { type: "zip", city: "Grand Rapids", zip: "49501" },
  { type: "state", state: "Minnesota" },
  { type: "zip", city: "Minneapolis", zip: "55401" },
  { type: "zip", city: "Saint Paul", zip: "55101" },
  { type: "state", state: "Wisconsin" },
  { type: "zip", city: "Milwaukee", zip: "53201" },
  { type: "zip", city: "Madison", zip: "53701" },
  { type: "state", state: "Missouri" },
  { type: "zip", city: "Kansas City", zip: "64101" },
  { type: "zip", city: "Saint Louis", zip: "63101" },
  { type: "state", state: "Tennessee" },
  { type: "zip", city: "Nashville", zip: "37201" },
  { type: "zip", city: "Memphis", zip: "38101" },
  { type: "state", state: "Louisiana" },
  { type: "zip", city: "New Orleans", zip: "70112" },
  { type: "zip", city: "Baton Rouge", zip: "70801" },
  { type: "state", state: "Utah" },
  { type: "zip", city: "Salt Lake City", zip: "84101" },
  { type: "zip", city: "Park City", zip: "84060" },
  { type: "state", state: "Montana" },
  { type: "zip", city: "Billings", zip: "59101" },
  { type: "zip", city: "Missoula", zip: "59801" },
  { type: "state", state: "Alaska" },
  { type: "zip", city: "Anchorage", zip: "99501" },
  { type: "zip", city: "Fairbanks", zip: "99701" },
  { type: "state", state: "Hawaii" },
  { type: "zip", city: "Honolulu", zip: "96801" },
  { type: "zip", city: "Hilo", zip: "96720" },
];

export const sampleLoremIpsum = [
  "Magna fugiat esse commodo sunt mollit est sint mollit ea amet pariatur exercitation cillum.",
  "Reprehenderit dolor magna tempor nostrud commodo mollit ullamco ipsum officia in deserunt consequat. Consequat consectetur fugiat deserunt fugiat officia enim nostrud. Enim esse ut aliquip id ipsum velit. Irure aliqua id eiusmod amet quis nulla nisi sunt veniam enim nulla id sint aliquip. Nulla magna culpa fugiat ea eu laboris sint tempor nisi elit in deserunt nisi.",
  "Ullamco reprehenderit esse pariatur non. Dolore aliquip nisi quis dolore sint ut culpa id consectetur. Dolor voluptate enim non laborum nisi non deserunt labore exercitation tempor. Nulla cupidatat voluptate nisi consectetur adipisicing culpa aute adipisicing occaecat laborum magna elit. Duis magna culpa duis elit culpa aliquip aute nisi ipsum fugiat.",
  "Tempor aliquip Lorem culpa duis laboris irure commodo duis duis minim incididunt anim. Aliqua consectetur cillum commodo amet in commodo ut. Tempor cupidatat duis incididunt deserunt cillum enim excepteur dolor non et do mollit mollit. Ipsum id nostrud ad nulla. Nostrud commodo cupidatat commodo consectetur sit voluptate incididunt qui elit duis nisi.",
  "Anim nulla qui consectetur pariatur reprehenderit aliqua voluptate dolore id.",
  "Ipsum consectetur est ipsum dolor fugiat quis deserunt veniam commodo exercitation. Reprehenderit sint culpa mollit labore ex esse ea fugiat consequat nulla magna cillum tempor. Culpa do sint laboris ex velit amet aliquip aliquip est. Sit sit proident duis eiusmod cillum cupidatat consequat esse do nulla Lorem quis. Aliquip enim commodo reprehenderit culpa incididunt est tempor.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
  "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
  "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
  "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
  "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
  "Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.",
  "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
  "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
  "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
  "Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.",
  "Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Gravida rutrum quisque non tellus orci ac auctor augue mauris augue neque gravida in fermentum et sollicitudin ac orci phasellus egestas tellus.",
  "Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam id leo in vitae turpis massa sed elementum.",
  "Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel risus commodo viverra.",
];
